// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2z5hxZze5wegNlEQe0c11sIzDm5ollU',
    appId: '1:1004904601906:web:e4ffdccbda5986fdcd5f2b',
    messagingSenderId: '1004904601906',
    projectId: 'atlas-news-app-3e854',
    authDomain: 'atlas-news-app-3e854.firebaseapp.com',
    storageBucket: 'atlas-news-app-3e854.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALe9D_A7AIon5bRXNdWHTWd1x_Tah5oVs',
    appId: '1:1004904601906:android:30c674710f1aba99cd5f2b',
    messagingSenderId: '1004904601906',
    projectId: 'atlas-news-app-3e854',
    storageBucket: 'atlas-news-app-3e854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcN9o9AO08BotSfRuFt4xcIC3kfGvr3s',
    appId: '1:1004904601906:ios:1a5c128d97881e44cd5f2b',
    messagingSenderId: '1004904601906',
    projectId: 'atlas-news-app-3e854',
    storageBucket: 'atlas-news-app-3e854.appspot.com',
    iosBundleId: 'com.example.atlasNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlcN9o9AO08BotSfRuFt4xcIC3kfGvr3s',
    appId: '1:1004904601906:ios:1a5c128d97881e44cd5f2b',
    messagingSenderId: '1004904601906',
    projectId: 'atlas-news-app-3e854',
    storageBucket: 'atlas-news-app-3e854.appspot.com',
    iosBundleId: 'com.example.atlasNewsApp',
  );
}
